# Generated by Django 5.1.2 on 2024-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsoporte',
            name='observacion',
            field=models.TextField(null=True),
        ),
    ]
