# Generated by Django 5.1 on 2024-10-20 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbodega',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallibro',
            name='history_user',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='fecha_Nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='nombre_autor',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_Publicacion',
            new_name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='bodega',
            name='codigo_bodega',
        ),
        migrations.AddField(
            model_name='libro',
            name='bodega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LibreriaApp.bodega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibreriaApp.autor'),
        ),
        migrations.DeleteModel(
            name='HistoricalAutor',
        ),
        migrations.DeleteModel(
            name='HistoricalBodega',
        ),
        migrations.DeleteModel(
            name='HistoricalLibro',
        ),
    ]
