# Generated by Django 5.1 on 2024-10-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibreriaApp', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
